[package]
name = "netro"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = {version = "0.28", features = ["socket", "net"]}
anyhow = "1"
libc = "0.2"
tokio = {version = "1.37", features  = ["full"]}
nom = "7.1.3"


[dev-dependencies]
rand = "0.8.5"
pnet = "0.34"
